In [2]:
import numpy
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from tqdm.notebook import tqdm

In [4]:
mnist_train = datasets.MNIST(root = "./dataset", train=True, transform=transforms.ToTensor(), download=False)
mnist_test = datasets.MNIST(root = "./dataset", train=False, transform=transforms.ToTensor(), download=False)

train_loader = torch.utils.data.DataLoader(mnist_train, batch_size = 100, shuffle=True)
test_loader = torch.utils.data.DataLoader(mnist_test, batch_size = 100, shuffle = False)

In [5]:
input_size = 784
hidden_size = [128,64]
output_size = 10

model = nn.Sequential(
    nn.Linear(input_size, hidden_size[0]),
    nn.ReLU(),
    nn.Linear(hidden_size[0], hidden_size[1]),
    nn.ReLU(),
    nn.Linear(hidden_size[1], output_size),
    nn.ReLU(),
    nn.LogSoftmax(dim=1)
)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.09)

epoch = 15
for e in range(epoch) :
    running_loss = 0;
    for images, labels in train_loader :
        images = images.view(images.shape[0], -1)
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output,labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print("Epoch %f : Training loss %f" %(e, running_loss/len(train_loader)))

    

Epoch 0.000000 : Training loss 1.497435
Epoch 1.000000 : Training loss 1.154831
Epoch 2.000000 : Training loss 1.080507
Epoch 3.000000 : Training loss 1.046133
Epoch 4.000000 : Training loss 1.022074
Epoch 5.000000 : Training loss 1.006467
Epoch 6.000000 : Training loss 0.996005
Epoch 7.000000 : Training loss 0.986807
Epoch 8.000000 : Training loss 0.979866
Epoch 9.000000 : Training loss 0.974099
Epoch 10.000000 : Training loss 0.969705
Epoch 11.000000 : Training loss 0.965637
Epoch 12.000000 : Training loss 0.962226
Epoch 13.000000 : Training loss 0.958519
Epoch 14.000000 : Training loss 0.955880


In [9]:
import torch
import torch.nn as nn

input = torch.randn(128,20)
print(input)
m = nn.Linear(20, 30)
output = m(input)
print(output)

print(len(input[0]))
print(len(output[0]))

tensor([[-0.2155,  0.6355, -0.4585,  ..., -1.0175,  0.5090,  0.8673],
        [ 0.4455, -2.2321, -0.1462,  ..., -0.0863,  0.7004,  0.0763],
        [ 0.1945, -0.5068,  0.5543,  ...,  1.6237, -0.2717, -0.4416],
        ...,
        [-0.3097,  0.5373,  0.1550,  ..., -0.8388, -1.6549,  1.1067],
        [-0.7787, -2.2326,  0.6982,  ...,  1.1478, -0.0400,  0.8598],
        [-2.1270,  3.0458, -1.6907,  ..., -1.3104,  0.1824, -0.4567]])
tensor([[ 0.2794,  0.1315, -0.2971,  ..., -0.1235,  0.9657,  0.1530],
        [-0.0811, -0.7334,  0.0047,  ..., -0.7465, -1.2888,  0.6615],
        [-0.4531, -0.9423,  0.3660,  ...,  0.4765,  0.3284, -0.6014],
        ...,
        [ 0.2134,  0.1610, -0.1909,  ...,  0.2956,  0.3455,  0.5896],
        [ 0.4703, -1.0039, -0.2413,  ..., -0.5743, -0.6220, -0.4136],
        [-0.2920,  1.3688,  0.2282,  ...,  1.2686, -0.3208,  0.8649]],
       grad_fn=<AddmmBackward0>)
20
30


In [13]:
import torch
import torch.nn as nn
import numpy as num
import random

student = [];
for i in range(0,10) :
    std_temp = [];
    for j in range(0,5) :
        std_temp.append(random.randint(0,100));
    student.append(std_temp);

model = nn.squential(
    nn.Linear(5,1)
);



[[24, 40, 86, 36, 9], [66, 16, 54, 15, 95], [51, 93, 17, 50, 28], [44, 80, 88, 60, 67], [99, 64, 70, 46, 30], [18, 29, 49, 60, 66], [51, 52, 90, 31, 90], [71, 1, 31, 24, 57], [49, 90, 90, 94, 92], [7, 49, 14, 94, 31]]


In [9]:
import numpy

x = 2*numpy.random.rand(100,1)
print(x)

[[0.12134652]
 [0.3692003 ]
 [1.01340611]
 [0.92617828]
 [0.41024183]
 [0.1682165 ]
 [0.49064722]
 [0.79322611]
 [1.63637874]
 [0.86378133]
 [0.70118728]
 [1.70308785]
 [1.81652378]
 [1.9743265 ]
 [1.7341688 ]
 [0.9416194 ]
 [0.68782739]
 [0.39881102]
 [1.26956529]
 [1.69970756]
 [1.38397577]
 [0.43872249]
 [0.51402804]
 [0.74393842]
 [0.80524159]
 [0.8101133 ]
 [0.66355289]
 [1.8211788 ]
 [1.75973694]
 [1.728843  ]
 [0.13011064]
 [0.47107168]
 [1.99444944]
 [1.97220108]
 [1.25442797]
 [1.63443514]
 [1.26866785]
 [1.77492714]
 [1.26007851]
 [1.99370119]
 [0.63708144]
 [1.46148472]
 [0.46626097]
 [0.1134569 ]
 [0.75306482]
 [0.86815984]
 [1.38773032]
 [0.86447202]
 [1.48646782]
 [1.38596475]
 [1.62359532]
 [1.00186672]
 [1.02113693]
 [1.96662869]
 [0.83244232]
 [1.39048222]
 [0.78091983]
 [1.10381024]
 [1.93073407]
 [0.45374284]
 [0.33788336]
 [1.86250941]
 [0.33051119]
 [0.84392416]
 [0.19212788]
 [1.22669921]
 [0.55018096]
 [1.41351982]
 [1.44065533]
 [1.20852772]
 [1.6588472 ]
 [0.98